config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/privacy', to: 'static_pages#privacy'
  get '/dashboard', to: 'dashboard#show'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/authorize', to: 'calendar#authorize'
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendar_events', to: 'calendar_events#new'
  resources :users, only: [:create]
  resources :activities, only: [:show]
  resources :entries, only: [:create, :edit, :update, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: :destroy
  resources :calendar_events, only: [:new]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DataHelper

  def show 
    @entry_balance = find_entry_balance
    @entries = current_user.entries
    @entry = Entry.new
    @activities = current_user.activities
    @contributors = current_user.activities.where({ category: 'contributor' }).order(:name)
    @subtractors = current_user.activities.where({ category: 'subtractor' }).order(:name)
    @contributor_sum = find_contributor_sum
    @subtractor_sum = find_subtractor_sum
    @past_week_chartkick_data = past_week_chartkick_data
    @past_month_chartkick_data = past_month_chartkick_data
  end

  private 

  def find_contributor_sum
    current_user.entries.joins(:activity).where(activities: { category: 'contributor' }).sum(:minutes)
  end

  def find_subtractor_sum
    current_user.entries.joins(:activity).where(activities: { category: 'subtractor' }).sum(:minutes)
  end

  def find_entry_balance
    contributor_sum = current_user.entries.joins(:activity).where(activities: { category: 'contributor' }).sum(:minutes)
    subtractor_sum = current_user.entries.joins(:activity).where(activities: { category: 'subtractor' }).sum(:minutes)
    contributor_sum - subtractor_sum
  end

  def past_week_chartkick_data
    [
      {
	name: 'Contributors',
	data: past_data("contributor", 7)
      },
      {
	name: 'Subtractors',
	data: past_data("subtractor", 7)
      }
    ] 
  end
  
  def past_month_chartkick_data
    [
      {
	name: 'Contributors',
	data: past_data("contributor", 30)
      },
      {
	name: 'Subtractors',
	data: past_data("subtractor", 30)
      }
    ] 
  end
end

app/views/dashboard/show.html.haml
.container#dashboard_container
  %p#text_xl.overview-text Overview for #{current_user.first_name}

  %button.button-primary#7_day_view Last 7 days
  %button.button-primary#30_day_view Last 30 days

  = line_chart @past_week_chartkick_data, { colors: ["#90EE90", "#FF7E75"], curve: false, defer: true, messages: {empty: "Insufficient data."} }

  = line_chart @past_month_chartkick_data, { colors: ["#90EE90", "#FF7E75"], curve: false, defer: true, messages: {empty: "Insufficient data."} }

  - if @activities.any?
    %p#text_lg{ data: { balance: true } } Balance: #{mins_to_condensed_time(@entry_balance.to_i)}

  - if session[:authorization]
    .pull-event-form.sm-screen-form
      = form_with(url: "/calendar_events", method: "get", local: true) do
        .time-inputs
          = label_tag('start', "Time Start")
          = select_datetime(Time.current.beginning_of_day, order: [:month, :day, :year], ampm: true, prefix: "start")
        .time-inputs
          = label_tag('end', "Time End")
          = select_datetime(Time.current.end_of_day, order: [:month, :day, :year], ampm: true, prefix: "end")
        = submit_tag("Search Calendar Events")
    
    .pull-event-form.lg-screen-form
      = form_with(url: "/calendar_events", method: "get", local: true) do
        .time-inputs
          = label_tag('start', "Time Start")
          = select_datetime(Time.current.beginning_of_day, order: [:month, :day, :year], ampm: true, prefix: "start")
        .time-inputs
          = label_tag('end', "Time End")
          = select_datetime(Time.current.end_of_day, order: [:month, :day, :year], ampm: true, prefix: "end")
        = submit_tag("Search Calendar Events")
  - else
    %button.sm-screen-button
      = link_to "Integrate Google Calendar", authorize_path
    %button.lg-screen-button
      = link_to "Integrate Google Calendar", authorize_path

  %p.separator
    %span or
  %p#text_xsm.lg-screen-separator or

  - if @activities.any?
    .sm-screen-form
      = form_for @entry do |f|
        = f.select(:activity_id, current_user.activities.map { |activity| [activity.name.titleize, activity.id] } + [["Add new...", ""]], {}, { data: { activity_name_select: true }})
        = text_field_tag :activity_name, nil, { placeholder: "Activity Name", class: "activity-name-input hidden" } 
        = select_tag :activity_category, options_for_select([['Contributor', 'contributor'], ['Subtractor', 'subtractor']]), { prompt: "Select type", class: "activity-category-input hidden" }
        = f.number_field :minutes, placeholder: "Minutes Spent", inputmode: "tel"
        = f.submit "Submit"

    .lg-screen-form
      = form_for @entry do |f|
        = f.select(:activity_id, current_user.activities.map { |activity| [activity.name.titleize, activity.id] } + [["Add new...", ""]], {}, { data: { activity_name_select: true }})
        = text_field_tag :activity_name, nil, { placeholder: "Activity Name", class: "activity-name-input hidden" } 
        = select_tag :activity_category, options_for_select([['Contributor', 'contributor'], ['Subtractor', 'subtractor']]), { prompt: "Select type", class: "activity-category-input hidden" }
        = f.number_field :minutes, placeholder: "Minutes Spent"
        = f.submit "Submit"
  - else
    %p No activities yet, add one!
    .sm-screen-form
      = form_for @entry  do |f|
        = text_field_tag :activity_name, nil, { placeholder: "Activity Name", class: "activity-name-input" } 
        = select_tag :activity_category, options_for_select([['Contributor', 'contributor'], ['Subtractor', 'subtractor']]), { prompt: "Select type" }
        = f.number_field :minutes, placeholder: "Minutes Spent", inputmode: "tel"
        = f.submit "Submit"
    
    .lg-screen-form
      = form_for @entry do |f|
        = text_field_tag :activity_name, nil, { placeholder: "Activity Name", class: "activity-name-input" } 
        = select_tag :activity_category, options_for_select([['Contributor', 'contributor'], ['Subtractor', 'subtractor']]), { prompt: "Select type" }
        = f.number_field :minutes, placeholder: "Minutes Spent"
        = f.submit "Submit"

  %h2.table-header#text_lg Contributors
  %table.u-full-width
    %thead
      %tr
        %th#text_sm Activity Name
        %th#text_sm Total Duration
    %tbody
      - @contributors.each do |activity|
        %tr
          %td= link_to(activity.name.titleize, activity_path(activity), { class: "activity-link", id: "text_xsm" })
          %td#text_xsm= mins_to_condensed_time(@entries.joins(:activity).where(activities: { name: activity.name }).sum(:minutes).to_i)
  
  %h2.table-header#text_lg Subtractors 
  %table.u-full-width
    %thead
      %tr
        %th#text_sm Activity Name
        %th#text_sm Total Duration
    %tbody
      - @subtractors.each do |activity|
        %tr
          %td= link_to(activity.name.titleize, activity_path(activity), { class: "activity-link", id: "text_xsm" })
          %td#text_xsm= mins_to_condensed_time(@entries.joins(:activity).where(activities: { name: activity.name }).sum(:minutes).to_i)