config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/privacy', to: 'static_pages#privacy'
  get '/dashboard', to: 'dashboard#show'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/authorize', to: 'calendar#authorize'
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendar_events', to: 'calendar_events#new'
  resources :users, only: [:create]
  resources :activities, only: [:show]
  resources :entries, only: [:create, :edit, :update, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: :destroy
  resources :calendar_events, only: [:new]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :entries, dependent: :destroy
  before_save { name.downcase! }

  validates :name, :category, presence: true
  validates :name, length: { maximum: 50 }
  validates_uniqueness_of :name, scope: :user_id
  validates :category, inclusion: { in: %w(contributor subtractor),
                                    message: "Must be contributor or subtractor." } 
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include DataHelper

  def show
    @activity = current_user.activities.find(params[:id])
    @past_week_activity_data = past_week_activity_data
    @past_mont_activity_data = past_month_activity_data
  end

  private

  def past_week_activity_data
    [
      {
        name: @activity.name.titleize,
        data: past_data(@activity.name, "activities.name", 7)
      }
    ] 
  end

  def past_month_activity_data
    [
      {
        name: @activity.name.titleize,
        data: past_data(@activity.name, "activities.name", 30)
      }
    ] 
  end
end

app/views/activities/show.html.haml
.container
  %h1#text_xl #{@activity.name.titleize}

  %button.button-primary#7_day_view Last 7 days
  %button.button-primary#30_day_view Last 30 days

  = line_chart @past_week_activity_data, { colors: ["#000"], curve: false, defer: true, messages: {empty: "Insufficient data."} }
  = line_chart @past_month_activity_data, { colors: ["#000"], curve: false, defer: true, messages: {empty: "Insufficient data."} }
  
  %h2.table-header#text_lg History
  %table.u-full-width
    %thead
      %tr
        %th#text_sm Date
        %th#text_sm Duration
        %th#text_sm Actions
    %tbody
      - @activity.entries.order('created_at DESC').each do |entry|
        %tr
          %td#text_xsm= entry.created_at.strftime("%b %e, %Y")
          %td#text_xsm= mins_to_condensed_time(entry.minutes.to_i)
          %td= link_to(image_tag("edit_icon.svg"), edit_entry_path(entry), id: "edit_icon") + link_to(image_tag("delete_icon.svg"), entry_path(entry), method: :delete, data: { confirm: 'Please confirm that you would like to delete this entry.' }, id: "delete_icon")
  