config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/privacy', to: 'static_pages#privacy'
  get '/dashboard', to: 'dashboard#show'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/authorize', to: 'calendar#authorize'
  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendar_events', to: 'calendar_events#new'
  resources :users, only: [:create]
  resources :activities, only: [:show]
  resources :entries, only: [:create, :edit, :update, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: :destroy
  resources :calendar_events, only: [:new]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Onward
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = javascript_include_tag 'https://cdn.jsdelivr.net/jquery/latest/jquery.min.js', defer: true
    = javascript_include_tag 'application', defer: true

  %body#body
    - unless controller_name == "password_resets"
      - if logged_in?
        %header#header
          = link_to image_tag("logo.jpg", { id: "logo" }), root_path
          %nav#nav_hamburger
            = label_tag("hamburger", "&#9776;".html_safe)
            = check_box_tag("hamburger")
            %ul
              %li= link_to "Dashboard", dashboard_path, id: "dashboard_link"
              %li= link_to "Privacy", privacy_path
              %li= mail_to "onwardappcx@gmail.com", "Contact"
              %li= link_to "Log Out", logout_path, method: :delete

        %header#lg_screen_header_if_logged_in
          = link_to image_tag("logo.jpg", { id: "logo" }), root_path
          %nav#lg_screen_nav
            %ul
              %li= link_to "Dashboard", dashboard_path, id: "dashboard_link"
              %li= link_to "Privacy", privacy_path
              %li= mail_to "onwardappcx@gmail.com", "Contact"
              %li= link_to "Log Out", logout_path, method: :delete
        %p.separator
      - else
        %header#lg_screen_header
          = link_to image_tag("logo.jpg", { id: "logo" }), root_path
          %nav#lg_screen_nav
            %ul
              %li
                = form_for(:session, url: login_path, html: { id: "login_form_if_not_logged_in", class: "lg-screen-form" }) do |f|
                  %li= f.email_field :email, placeholder: "Email"
                  %li= f.password_field :password, placeholder: "Password"
                  %li
                    = f.label :remember_me, { class: "remember-checkbox" } do
                      %span.label-body Remember?
                      = f.check_box :remember_me
                  %li= f.submit "Log In"
                  %li= link_to "Sign Up", signup_path
                  %li= link_to "Forgot Password", new_password_reset_path
                  %li= link_to "Privacy", privacy_path
                  %li= mail_to "onwardappcx@gmail.com", "Contact"
        %p.separator

    - flash.each do |message_type, message|
      = content_tag(:p, message, id: "text_med", class: "alert alert-#{message_type}")

    = yield